name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.8, 3.9]
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Grab poetry
      uses: dschep/install-poetry-action@v1.2
    - name: Cache virtualenv
      uses: actions/cache@v1
      id: cache
      with:
        path: ~/.virtualenv
        key: poetry-$
        restore-keys: |
          poetry-$
    - name: Install dependencies
      run: poetry install

    - name: Test
      run: bash bin.sh test
